# Generated by Django 6.0.5 on 2026-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_taken', models.IntegerField(default=0)),
                ('first_step_date', models.DateTimeField(verbose_name='date stepped')),
            ],
        ),
    ]
